on:
  release:
    types: [released]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set VERSION variable from tag
        run: |
          REF_NAME=${{ github.ref_name }}
          echo "VERSION=${REF_NAME#v}" >> $GITHUB_ENV
      - name: Build
        run: dotnet build --configuration Release /p:Version=${VERSION}
        working-directory: .
      - name: Test
        run: dotnet test --configuration Release /p:Version=${VERSION} --no-build
        working-directory: .
      - name: Pack
        run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output .
        working-directory: Ares.Toolkit.Device
      - name: Push
        run: |
          dotnet nuget push Ares.Toolkit.Device.${VERSION}.nupkg \
          --api-key ${NUGET_API_TOKEN} \
          --source https://api.nuget.org/v3/index.json \
          --skip-duplicate
        working-directory: Ares.Toolkit.Device
        env:
          NUGET_API_TOKEN: ${{ secrets.NUGET_API_TOKEN }}
