on:
  release:
    types: [released]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Build
        run: dotnet build --configuration Release /p:Version=${VERSION}
        working-directory: dotnet
      - name: Test
        run: dotnet test --configuration Release /p:Version=${VERSION} --no-build
        working-directory: dotnet
      - name: Pack
        run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output .
        working-directory: dotnet/Ares.Toolkit.Device
      - name: Push
        run: |
          dotnet nuget push Ares.Toolkit.Device.${VERSION}.nupkg \
          --api-key ${NUGET_TOKEN} \
          --source https://api.nuget.org/v3/index.json \
          --skip-duplicate
        working-directory: dotnet/Ares.Toolkit.Device
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_API_KEY }}
